### ISSUE TITLE
Machine Learning Summer School (MLSS Moscow)

### ISSUE THREAD

**Issue by rodrigorivera** [sshkhr/awesome-mlss#13]
Hi, 

thank you for the great work compiling the list. I would like to point out regarding the "MLSS Moscow". The school is also a Machine Learning Summer School from the MLSS series (http://mlss.cc) same as the one in London and Stellenbosch this year. 

Would it be please possible to adjust the name to Machine Learning Summer School (MLSS Moscow)?

Further, regarding the financial support, best applications will have accommodation costs fully covered and no registration fees. In addition to this, there are full and partial (25%) stipends for strong applicants.

Would it be please possible to add that there is also an accommodation stipend in addition to the registration stipend?

**Comment by sshkhr** [comment]
Thanks a lot for pointing this out and for the PR. Requested changes are now reflected
