### ISSUE TITLE
Summer Institute

### ISSUE THREAD

**Issue by silvavn** [sshkhr/awesome-mlss#17]
Summer institute is an AI/Ethics Summer School that will run just before DLRL Summer School in Edmonton Alberta. No funding provided.
https://dlrlsummerschool.ca/the-summer-institute/

**Comment by sshkhr** [comment]
I think this may have been a part of the DLRL summer school. The link doesn't work anymore for me so I have no way to verify. I will add if it is held again by CIFAR
