### ISSUE TITLE
Beirut AI Bootcamp

### ISSUE THREAD

**Issue by ObeidaElJundi** [sshkhr/awesome-mlss#21]
You may also wanna add Beirut AI Summer Bootcamp: https://beirutai.org/bootcamp/
Unfortunately, this session already started today, but there will be more future sessions.
Beirut AI (http://beirut.city.ai/) is a local community that is part of a global network of AI communities around the globe (city.ai). Its mission is to accelerate the adoption of AI, in all its forms, in businesses and start-ups, what we call Applied AI. Beirut AI wants to enable everyone in Lebanon to have access to the tools and knowledge to apply Artificial Intelligence. 
Beirut AI hosts events to share the knowledge of practitioners (people who used AI before) with anyone interested in applying AI or just learning about it. It also hosts a technical workshop approximately once a month where we work hands-on on Data Science or Machine Learning problems. Check the website & the following Github repo for previous activities: https://github.com/BeirutAI/

**Comment by sshkhr** [comment]
Thanks a lot for sharing. This looks like a great initiative but it seems more of an academic+industrial initiative in the style of meetups than a summer school (which is more academically oriented). Hence I feel this doesn't belong here.
