### ISSUE TITLE
Bumblekite: Machine learning summer school in healthcare and biosciences in Zurich, Switzerland

### ISSUE THREAD

**Issue by thwismer** [sshkhr/awesome-mlss#25]
Please add this new MLSS that is coming up in 2020: Machine learning summer school in healthcare and biosciences

19th July - 28th July 2020
ETH Zurich, Zurich, Switzerland

[Bumblekite](https://bumblekite.four-corp.com/?utm_source=github&utm_medium=referral&utm_campaign=main)

**Comment by sshkhr** [comment]
Thanks for bringing this to attention. I'll add this once more details become available.

**Comment by thwismer** [comment]
Thank you very much. More details are available now:

- Name/URL: [bumblekite](https://bumblekite.four-corp.com/?utm_source=github&utm_medium=referral&utm_campaign=main) – Machine learning summer school in healthcare and biosciences
- Location: Zurich, Switzerland
- Organiser: [Four](https://four-corp.com/)
- Dates: 19th July – 28th July 2020
- Deadline: March 15th 2020
- Fee: $600~$2900
- Aid (Travel Grants etc): Full and partial [scholarships](https://bumblekite.four-corp.com/application#scholarships) covering part or the entire cost of participation

Thanks for adding :+1:

**Comment by sshkhr** [comment]
Added :+1:
