### ISSUE TITLE
Add Google Research AI Summit

### ISSUE THREAD

**Issue by abhishek-t-naive** [sshkhr/awesome-mlss#46]
You can add Google Research India AI summit [Check it out here](https://sites.google.com/view/aisummerschool2020/application?authuser=0) in the list.

Deadline is 26th June. Results expected by the end of July

**Comment by sshkhr** [comment]
Thanks for the suggestion. Could you please share a link?

**Comment by abhishek-t-naive** [comment]
I have just updated my initial comment with the link

**Comment by sara-02** [comment]
Not sure if this was added to the list or not, but the applications closed on June 26th.

**Comment by abhishek-t-naive** [comment]
Yeah. I think I will close it.
