### ISSUE TITLE
Few More Virtual Deep Learning Schools for 2020

### ISSUE THREAD

**Issue by sara-02** [sshkhr/awesome-mlss#51]
Just wanted to share 2 more DL online schools I came across:

1. http://2020.dl-lab.eu/virtual-summer-school-on-deep-learning/

2. http://ml-school.uni-koeln.de/ 

Registrations are still open for both

**Comment by sshkhr** [comment]
Thanks for your contribution! The second one has been added. Please feel free to open a PR for any additional requests

**Comment by Data-Spoiler** [comment]
Also, I come across some other summer schools for AI and DL:
1. School of ai: Pi school, Rome [https://picampus-school.com/programme/school-of-ai/]
2. DLAI3, Thailand [https://deeplearningandaiwinterschool.github.io/]
3. AI Summer School 2019 Singapore [https://aisummerschool.aisingapore.org/]
Registrations for 1st one are still open. but the registrations are closed for others.

**Comment by sshkhr** [comment]
Thanks again!
