### ISSUE TITLE
Can you add more summer schools for 2021?

### ISSUE THREAD

**Issue by datonefaridze** [sshkhr/awesome-mlss#56]
Hello, I have searched throught the internet and haven't found summer schools in AI in 2021. would you be able to add 2021 schools programs? thanks in advance

**Comment by sshkhr** [comment]
Hi @datonefaridze I will be more than happy to add any schools you have found. Please send a PR (or share the links) of the schools you wanted to see in the list

**Comment by datonefaridze** [comment]
@sshkhr  hello, currently i am looking for summer schools or any research opportunities, here is DAAD program link: **https://www.daad.org/en/**   but unfortunately i am not eligible to take part in any of these programs because i am not from USA. they have programs for students outside of US but programs are not connected with Computer Science, Irony :D :D.

**Comment by dreamflasher** [comment]
Some 2021 ones:
https://www.oxfordml.school/application
https://dlrl.ca/
https://www.eeml.eu/
http://mlss.cc/

**Comment by sshkhr** [comment]
Thanks a ton @dreamflasher!  I will add these today :-)

**Comment by aymuos15** [comment]
http://cvit.iiit.ac.in/summerschool2021/register.php - The registrations for this are still open!
