### ISSUE TITLE
Can you possible add this camp to your list?

### ISSUE THREAD

**Issue by HaripriyaMehta** [sshkhr/awesome-mlss#57]
MehtA+ Digital Humanities Machine Learning Bootcamp

Taught by MIT, Stanford and Columbia alumni, this camp provides students with expert instruction in cutting edge university-level AI/Machine Learning, which students will then apply to Digital Humanities projects run by professors from top US and International universities, including University of Bologna (Italy), University of Buffalo SUNY, Northeastern University, Haverford College and Kenyon College among others. Examples of projects that students will be working on include using machine learning to determine authorship of handwritten 19th century Italian texts and exploring tweets for dialectic change in Spanish language. Students will potentially receive an opportunity to have their work published in professional academic journals.

Who it’s for: Grades 8 - 12
Length of program: 6 weeks
Locations: Online
Upcoming start dates: July 21, 2021

More information about the camp can be found here: https://mehtaplustutoring.com

**Comment by sshkhr** [comment]
Thank you for sharing your boot camp Haripriya. The awesome-mlss list is directed more towards graduate students, researchers and industry professionals already working in the field of machine learning. The bootcamp's focus is quite different compared to the focus of the other summer schools on the list so I don't think its a great fit. I feel https://github.com/theodesp/awesome-coding-camps might be a better fit for your submission.
