### ISSUE TITLE
I can't find open application form on https://dlrl.ca/

### ISSUE THREAD

**Issue by datonefaridze** [sshkhr/awesome-mlss#60]
Hello, you have written that application is open on deep reinforcement summer school by cifar, but unfortunately i can't find form to fill, so can you help me? @sshkhr

**Comment by hazratali** [comment]
It seems applications are not open yet. Keeping checking their website [https://dlrl.ca/](https://dlrl.ca/)

**Comment by datonefaridze** [comment]
@hazratali  okay thanks

**Comment by hazratali** [comment]
@datonefaridze APPLICATIONS ARE OPEN NOW. DEADLINE IS 9 APRIL 2021.
