### ISSUE TITLE
Add summer schools

### ISSUE THREAD

**Issue by chthr** [sshkhr/awesome-mlss#69]
The following MLSS are missing:
- [Leibniz MMS Summer School](https://www.wias-berlin.de/research/Leibniz-MMS/SummerSchool20/)
- [ACDL 2021](https://acdl2021.icas.cc/)
Related fields:
- [AI & law Summer School 2021](https://aiandlawschool.eui.eu/)

**Comment by gmberton** [comment]
Closing issues of already finished summer schools
