### ISSUE TITLE
Is anyone accepted by CIFAR?

### ISSUE THREAD

**Issue by datonefaridze** [sshkhr/awesome-mlss#74]
Hello, this isn't issue, i just couldn't find better place to ask. I was rejected from CIFAR and i am interested if someone from this space was accepted. if so let me know

**Comment by sshkhr** [comment]
I have a labmate who was accepted. Do you have any particular questions that you'd like to ask?

**Comment by datonefaridze** [comment]
@sshkhr yes, i really wanted to attend this. only 1 question i had was: are lectures recorded?

**Comment by sshkhr** [comment]
Lectures from 2020 are available here: https://dlrl.ca/about/2020-highlights/
