### ISSUE TITLE
Lviv Data Science Summer School 2021

### ISSUE THREAD

**Issue by mmarkomortensen** [sshkhr/awesome-mlss#76]
Hi!

My name is Mariia Marko-Mortensen and I am the coordinator of Lviv Data Science Summer School 2021. Lviv Data Science Summer School is an educational initiative of the Faculty of Applied Sciences of the Ukrainian Catholic University. I found your page and we will appreciate it a lot if you add our Summer School to this list. It's a yearly project and this year it will be already 6th Summer School.

Here is our webpage: https://apps.ucu.edu.ua/en/summerschool-ds/

Let me know if you are interested in this

**Comment by gmberton** [comment]
Closing issues about past schools
